### ISSUE TITLE
debian11 arm64设备启动出现错误A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by lsearsea** [MaaAssistantArknights/MaaX#138]
### 问题描述

![截图_2023-04-25_21-02-09](https://user-images.githubusercontent.com/88135767/234284710-47311d35-f26c-42c5-bf7d-9599fc07ab1e.png)
如图
_libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip
libGL error: failed to create dri screen
libGL error: failed to load driver: rockchip_
这一段可以忽略(

### 日志文件
orangepi@orangepi5:/usr/maa$ ./maa-x
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/maa/resources/app/node_modules/@tigerconnect/ffi-napi/build/Release/ffi_bindings.node: æ æ³æ	å¼å
±äº«å¯¹è±¡æä»¶: æ²¡æ	é£ä¸ªæä»¶æç
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at load (/usr/maa/resources/app/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/usr/maa/resources/app/node_modules/@tigerconnect/ffi-napi/lib/bindings.js:8:43)
[23832:0425/205909.090155:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization

**Comment by ChingCdesu** [comment]
这个问题解决了吗

**Comment by lsearsea** [comment]
> 这个问题解决了吗

beta.7版本还是一样的,不过git下来后能打开pnpm dev,执行其他的start,bulid之类的不行

**Comment by ChingCdesu** [comment]
可能你gpu驱动不太正常还是啥的，试试其他依赖于OpenGL的软件，或者测试一下OpenGL的功能是否正常
maa-x在我的kali上是可以正常运行的
