### ISSUE TITLE
实机通过usb连接成功但启动失败

### ISSUE THREAD

**Issue by kuzen** [MaaAssistantArknights/MaaX#163]
### 问题描述

通过usb连接实机设备，`adb devices`能够显示设备，maax启动后左栏能够自动获取到当前设备名，与`adb shell settings get secure android_id`结果一致，点击开始任务后报错。

### 日志文件

```
2023-05-22 11:41:03.638  SILLY [main resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.StorageManager:set 
2023-05-22 11:41:03.639  SILLY [main resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.StorageManager:set 
2023-05-22 11:41:03.700  SILLY [main resources/app/packages/main/storageManager/index.ts:68 ks.<anonymous>] configuration saved 
2023-05-22 11:41:25.264  SILLY [main resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.StorageManager:set 
2023-05-22 11:41:25.332  SILLY [main resources/app/packages/main/storageManager/index.ts:68 ks.<anonymous>] configuration saved 
2023-05-22 11:41:26.104  SILLY [main resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.CoreLoader:stop 
2023-05-22 11:41:26.104  WARN [main resources/app/packages/main/coreLoader/index.ts:443  pn.Stop] [Stop] uuid not exists 6e7d354bddca8646 
2023-05-22 11:41:26.512  SILLY [main resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.Util:LogInfo 
2023-05-22 11:41:26.512  INFO  [renderer resources/app/packages/main/utils/logger.ts:62 undefined.<anonymous>] change device status 6e7d354bddca8646 tasking -> connected 
2023-05-22 11:41:26.513  SILLY [main resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.StorageManager:set 
2023-05-22 11:41:26.514  SILLY [main resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.StorageManager:set 
2023-05-22 11:41:26.564  SILLY [main resources/app/packages/main/storageManager/index.ts:68 ks.<anonymous>] configuration saved 
2023-05-22 11:41:27.541  SILLY [main resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.Util:LogInfo 
2023-05-22 11:41:27.541  INFO  [renderer resources/app/packages/main/utils/logger.ts:62 undefined.<anonymous>] change device status 6e7d354bddca8646 connected -> tasking 
2023-05-22 11:41:27.542  SILLY [main resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.CoreLoader:appendTask 
Error occurred in handler for 'main.CoreLoader:appendTask': TypeError: error setting argument 1 - writePointer: Buffer instance expected as third argument
    at Object.writePointer (/home/uto/private/maa-x-linux-x64/resources/app/node_modules/@tigerconnect/ref-napi/lib/ref.js:754:11)
    at Object.set (/home/uto/private/maa-x-linux-x64/resources/app/node_modules/@tigerconnect/ref-napi/lib/ref.js:494:13)
    at Object.alloc (/home/uto/private/maa-x-linux-x64/resources/app/node_modules/@tigerconnect/ref-napi/lib/ref.js:526:13)
    at Object.proxy [as AsstAppendTask] (/home/uto/private/maa-x-linux-x64/resources/app/node_modules/@tigerconnect/ffi-napi/lib/_foreign_function.js:50:28)
    at pn.AppendTask (/home/uto/private/maa-x-linux-x64/resources/app/dist/main/index-8d8311b6.js:46:23584)
    at main.CoreLoader:appendTask (/home/uto/private/maa-x-linux-x64/resources/app/dist/main/index-8d8311b6.js:46:26621)
    at /home/uto/private/maa-x-linux-x64/resources/app/dist/main/index-8d8311b6.js:46:14935
    at node:electron/js2c/browser_init:189:579
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11433)
    at EventEmitter.emit (node:events:527:28)
```

### 截图

![image](https://github.com/MaaAssistantArknights/MaaX/assets/16202160/e3c8a8b9-9da8-4fbc-a449-946ae13bd76a)

### 还有别的吗？

ArchLinux 6.3.2-arch1-1
MaaX v2.0.0-beta.6
MaaCore v4.17.1

**Comment by ChingCdesu** [comment]
@bakashigure 这个好像是core不适配还是啥的

**Comment by kuzen** [comment]
maacore用的是aur上的maa，然后软链接到`~/.config/maa-x/core/`

**Comment by bakashigure** [comment]
试一下新版(beta10)看看问题是否解决

**Comment by kuzen** [comment]
无法启动任务，log显示重复创建，切换touch_mode也是一样。

```
2023-05-27 04:59:44.757  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.Util:LogInfo 
2023-05-27 04:59:44.757  INFO  [renderer out/maa-x-linux-x64/resources/app/packages/main/utils/logger.ts:62 undefined.<anonymous>] change device status 6e7d354bddca8646 connecting -> waitingTask 
2023-05-27 04:59:44.758  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.CoreLoader:initCoreAsync 
2023-05-27 04:59:44.758  WARN [main out/maa-x-linux-x64/resources/app/packages/main/hooks/asst.ts:42  main.CoreLoader:initCoreAsync] 重复创建 {"address":"10.102.83.58:40629","uuid":"6e7d354bddca8646","adb_path":"/home/uto/.config/maa-x/platform-tools/adb","config":"General","touch_mode":"adb"} 
2023-05-27 04:59:44.759  WARN [main out/maa-x-linux-x64/resources/app/packages/main/hooks/asst.ts:44  main.CoreLoader:initCoreAsync] Set touch mode failed adb 
2023-05-27 04:59:44.759  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.StorageManager:set 
2023-05-27 04:59:44.811  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/storageManager/index.ts:68 ks.<anonymous>] configuration saved 
```

ArchLinux / kernel 6.3.2-arch1-1
MaaX v2.0.0-beta.10
MaaCore 4.19.0beta.1

**Comment by kuzen** [comment]
补充，感觉是连接上了但是maax认为没连上/或者是有问题而断开了。单独使用`adb connect`正常

首先输入ip:端口，并点击连接，一直显示正在连接，但log显示如下：
```
2023-05-28 01:57:59.985  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.DeviceDetector:getDeviceUuid 
2023-05-28 01:57:59.985  INFO  [main out/maa-x-linux-x64/resources/app/packages/main/utils/shell.ts:56  df] exec: /home/uto/.config/maa-x/platform-tools/adb connect 10.102.83.58:40867 
2023-05-28 01:58:00.146  INFO  [main out/maa-x-linux-x64/resources/app/packages/main/utils/shell.ts:70  df] 
{
  stderr: '',
  stdout: 'connected to 10.102.83.58:40867'
}
2023-05-28 01:58:00.148  INFO  [main out/maa-x-linux-x64/resources/app/packages/main/utils/shell.ts:29  vr] exec: "/home/uto/.config/maa-x/platform-tools/adb" -s 10.102.83.58:40867 shell settings get secure android_id 
2023-05-28 01:58:00.199  INFO  [main out/maa-x-linux-x64/resources/app/packages/main/utils/shell.ts:44  vr] 
{
  stderr: '',
  stdout: '6e7d354bddca8646'
}
2023-05-28 01:58:00.200  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.DeviceDetector:getAdbPath 
2023-05-28 01:58:00.201  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.Util:LogDebug 
2023-05-28 01:58:00.201  DEBUG [renderer out/maa-x-linux-x64/resources/app/packages/main/utils/logger.ts:56 undefined.<anonymous>] uuid 6e7d354bddca8646  origin status: unknown 
2023-05-28 01:58:00.201  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.StorageManager:set 
2023-05-28 01:58:00.203  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.Util:LogInfo 
2023-05-28 01:58:00.203  INFO  [renderer out/maa-x-linux-x64/resources/app/packages/main/utils/logger.ts:62 undefined.<anonymous>] change device status 6e7d354bddca8646 available -> connecting 
2023-05-28 01:58:00.203  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.CoreLoader:initCoreAsync 
2023-05-28 01:58:00.204  WARN [main out/maa-x-linux-x64/resources/app/packages/main/hooks/asst.ts:44  main.CoreLoader:initCoreAsync] Set touch mode failed adb 
2023-05-28 01:58:00.204  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.StorageManager:set 
2023-05-28 01:58:00.255  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/storageManager/index.ts:68 ks.<anonymous>] configuration saved 
2023-05-28 01:58:16.470  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.Util:LogInfo 
2023-05-28 01:58:16.470  INFO  [renderer out/maa-x-linux-x64/resources/app/packages/main/utils/logger.ts:62 undefined.<anonymous>] change device status 6e7d354bddca8646 connecting -> waitingTask 
2023-05-28 01:58:16.471  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.CoreLoader:initCoreAsync 
2023-05-28 01:58:16.471  WARN [main out/maa-x-linux-x64/resources/app/packages/main/hooks/asst.ts:42  main.CoreLoader:initCoreAsync] 重复创建 {"address":"10.102.83.58:40867","uuid":"6e7d354bddca8646","adb_path":"/home/uto/.config/maa-x/platform-tools/adb","config":"General","touch_mode":"adb"} 
2023-05-28 01:58:16.472  WARN [main out/maa-x-linux-x64/resources/app/packages/main/hooks/asst.ts:44  main.CoreLoader:initCoreAsync] Set touch mode failed adb 
2023-05-28 01:58:16.473  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.StorageManager:set 
```
```
Android Debug Bridge version 1.0.41
Version 34.0.1-android-tools
```

**Comment by ChingCdesu** [comment]
实体机确实可能会有一点点小问题，貌似现在国产的一些手机都默认不允许adb截屏了，可能core那边无法截到图就挂了

**Comment by bakashigure** [comment]
> 补充，感觉是连接上了但是maax认为没连上/或者是有问题而断开了。单独使用`adb connect`正常
> 
> 首先输入ip:端口，并点击连接，一直显示正在连接，但log显示如下：
> 
> ```
> 2023-05-28 01:57:59.985  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.DeviceDetector:getDeviceUuid 
> 2023-05-28 01:57:59.985  INFO  [main out/maa-x-linux-x64/resources/app/packages/main/utils/shell.ts:56  df] exec: /home/uto/.config/maa-x/platform-tools/adb connect 10.102.83.58:40867 
> 2023-05-28 01:58:00.146  INFO  [main out/maa-x-linux-x64/resources/app/packages/main/utils/shell.ts:70  df] 
> {
>   stderr: '',
>   stdout: 'connected to 10.102.83.58:40867'
> }
> 2023-05-28 01:58:00.148  INFO  [main out/maa-x-linux-x64/resources/app/packages/main/utils/shell.ts:29  vr] exec: "/home/uto/.config/maa-x/platform-tools/adb" -s 10.102.83.58:40867 shell settings get secure android_id 
> 2023-05-28 01:58:00.199  INFO  [main out/maa-x-linux-x64/resources/app/packages/main/utils/shell.ts:44  vr] 
> {
>   stderr: '',
>   stdout: '6e7d354bddca8646'
> }
> 2023-05-28 01:58:00.200  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.DeviceDetector:getAdbPath 
> 2023-05-28 01:58:00.201  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.Util:LogDebug 
> 2023-05-28 01:58:00.201  DEBUG [renderer out/maa-x-linux-x64/resources/app/packages/main/utils/logger.ts:56 undefined.<anonymous>] uuid 6e7d354bddca8646  origin status: unknown 
> 2023-05-28 01:58:00.201  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.StorageManager:set 
> 2023-05-28 01:58:00.203  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.Util:LogInfo 
> 2023-05-28 01:58:00.203  INFO  [renderer out/maa-x-linux-x64/resources/app/packages/main/utils/logger.ts:62 undefined.<anonymous>] change device status 6e7d354bddca8646 available -> connecting 
> 2023-05-28 01:58:00.203  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.CoreLoader:initCoreAsync 
> 2023-05-28 01:58:00.204  WARN [main out/maa-x-linux-x64/resources/app/packages/main/hooks/asst.ts:44  main.CoreLoader:initCoreAsync] Set touch mode failed adb 
> 2023-05-28 01:58:00.204  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/utils/ipc-main.ts:25 undefined.<anonymous>] Receive ipcMain event: main.StorageManager:set 
> 2023-05-28 01:58:00.255  SILLY [main out/maa-x-linux-x64/resources/app/packages/main/storageManager/index.ts:68 ks.<anonymous>] configuration saved 
> ```
> 
> ```
> Android Debug Bridge version 1.0.41
> Version 34.0.1-android-tools
> ```

`maa-x`只判定能取得`UUID`就认为可以连接上,  `core`的判定就复杂的多, 需要看`UUID`, `截图方式`等
麻烦传一份`core`的日志, 在`maa-x`的设置下方可以快捷打开
